[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "ollama serve"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "ollama"
internal_port = 11434
routes = [
  { type = "http", path = "/" }
]
